// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AdsKeywordDatum
{
    public int Id { get; set; }

    public int AdsSearchRequestId { get; set; }

    public string Keyword { get; set; }

    public string AvgSearchVolume { get; set; }

    public string Competition { get; set; }

    public string LowBid { get; set; }

    public string HighBid { get; set; }

    public bool AiSuggestion { get; set; }

    public string AiMessage { get; set; }

    public virtual AdsSearchRequest AdsSearchRequest { get; set; }
}