// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class AdsKeywordDatum
{
    [Key]
    public int Id { get; set; }

    public int AdsSearchRequestId { get; set; }

    [StringLength(255)]
    public string Keyword { get; set; }

    [StringLength(50)]
    public string AvgSearchVolume { get; set; }

    [StringLength(50)]
    public string Competition { get; set; }

    [StringLength(50)]
    public string LowBid { get; set; }

    [StringLength(50)]
    public string HighBid { get; set; }

    public bool AiSuggestion { get; set; }

    public string AiMessage { get; set; }

    [ForeignKey("AdsSearchRequestId")]
    [InverseProperty("AdsKeywordData")]
    public virtual AdsSearchRequest AdsSearchRequest { get; set; }
}