// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AdsSearchRequest
{
    public int Id { get; set; }

    public string QueryList { get; set; }

    public byte[] QueryHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AdsKeywordDatum> AdsKeywordData { get; set; } = new List<AdsKeywordDatum>();

    public virtual ICollection<QueryHistory> QueryHistories { get; set; } = new List<QueryHistory>();
}