// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AnalysisSnapshot
{
    public int SnapshotID { get; set; }

    public int AnalysisCacheID { get; set; }

    public string PageSpeedResponse { get; set; }

    public DateTime AnalyzedAt { get; set; }

    public DateTime ArchivedAt { get; set; }

    public virtual AnalysisCache AnalysisCache { get; set; }
}