// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AnalysisCache
{
    public int AnalysisCacheID { get; set; }

    public string Url { get; set; }

    public string NormalizedUrl { get; set; }

    public string Strategy { get; set; }

    public string PageSpeedResponse { get; set; }

    public string GeneralAssessment { get; set; }

    public string Suggestion { get; set; }

    public DateTime LastAnalyzedAt { get; set; }

    public virtual ICollection<AnalysisSnapshot> AnalysisSnapshots { get; set; } = new List<AnalysisSnapshot>();

    public virtual ICollection<Element> Elements { get; set; } = new List<Element>();

    public virtual ICollection<MetaDataAnalysis> MetaDataAnalyses { get; set; } = new List<MetaDataAnalysis>();

    public virtual ICollection<PerformanceHistory> PerformanceHistories { get; set; } = new List<PerformanceHistory>();
}