// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class ContentOptimization
{
    [Key]
    public int ContentOptimizationID { get; set; }

    public int UserID { get; set; }

    [StringLength(50)]
    public string Model { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Keyword { get; set; }

    [Required]
    public string OriginalContent { get; set; }

    [Required]
    [StringLength(20)]
    public string ContentLenght { get; set; }

    public int OptimizationLevel { get; set; }

    [Required]
    [StringLength(20)]
    public string ReadabilityLevel { get; set; }

    public string OptimizedContent { get; set; }

    public int? SEOScore { get; set; }

    public int? Readability { get; set; }

    public int? Engagement { get; set; }

    public int? Originality { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("ContentOptimizations")]
    public virtual User User { get; set; }
}