// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class ContentOptimization
{
    public int ContentOptimizationID { get; set; }

    public int UserID { get; set; }

    public string Model { get; set; }

    public string UserRequest { get; set; }

    public string AIResponse { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual User User { get; set; }
}