// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class Element
{
    [Key]
    public int ElementID { get; set; }

    public int PerformanceID { get; set; }

    [StringLength(50)]
    public string TagName { get; set; }

    [StringLength(255)]
    public string Attribute { get; set; }

    public string InnerText { get; set; }

    public string OuterHTML { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    public bool Important { get; set; }

    public bool HasSuggestion { get; set; }

    public string AIRecommendation { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("PerformanceID")]
    [InverseProperty("Elements")]
    public virtual Performance Performance { get; set; }
}