// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class Element
{
    public int ElementID { get; set; }

    public int AnalysisCacheID { get; set; }

    public string TagName { get; set; }

    public string InnerText { get; set; }

    public string OuterHTML { get; set; }

    public bool Important { get; set; }

    public bool HasSuggestion { get; set; }

    public string AIRecommendation { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual AnalysisCache AnalysisCache { get; set; }
}