// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class FeatureInformation
{
    [Key]
    public int InformationID { get; set; }

    public int FeatureID { get; set; }

    [StringLength(100)]
    public string InformationFeature { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("FeatureID")]
    [InverseProperty("FeatureInformations")]
    public virtual Feature Feature { get; set; }
}