// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class FeedbackMessage
{
    public int MessageID { get; set; }

    public int FeedbackID { get; set; }

    public int SenderID { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Feedback Feedback { get; set; }

    public virtual User Sender { get; set; }
}