// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class GeminiKey
{
    public int Id { get; set; }

    public string ApiKey { get; set; }

    public string KeyName { get; set; }

    public bool IsActive { get; set; }

    public int RpmLimit { get; set; }

    public int TpmLimit { get; set; }

    public int RpdLimit { get; set; }

    public int RequestsUsedToday { get; set; }

    public long TokensUsedToday { get; set; }

    public DateTime LastResetDate { get; set; }

    public DateTime? RateLimitedUntil { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}