// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SEOBoostAI.Repository.Models;

[Index("IsActive", "RequestsUsedToday", "RateLimitedUntil", Name = "IX_GeminiKeys_GetAvailable")]
public partial class GeminiKey
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Chuỗi API Key thực tế từ Google AI Studio
    /// </summary>
    /// <example>AIzaSyD-xxxxxxxxxxxxxxxx</example>
    [Required]
    [StringLength(600)]
    public string ApiKey { get; set; }

    /// <summary>
    /// Tên gợi nhớ cho Key (Ví dụ: Key Marketing)
    /// </summary>
    [StringLength(100)]
    [DefaultValue("Gemini AI Key")]
    public string KeyName { get; set; }

    public bool IsActive { get; set; }

    /// <summary>
    /// Giới hạn số request mỗi phút (Requests Per Minute).
    /// </summary>
    /// <remarks>
    /// Đối với gói Free giới hạn thường là 2-5 RPM. Gói trả phí có thể cao hơn.
    /// </remarks>
    /// <example>5</example>
    [Required]
    [Range(0, 5, ErrorMessage = "Giới hạn của RPM(request per minute) là từ 0 đến 5")]
    [DefaultValue(5)]
    public int RpmLimit { get; set; }

    /// <summary>
    /// Giới hạn số token mỗi phút (Tokens Per Minute).
    /// </summary>
    /// <remarks>
    /// Token là đơn vị tính phí của AI. 1000 tokens ~= 750 từ.
    /// </remarks>
    /// <example>32000</example>
    [Required]
    [Range(0, 250000, ErrorMessage = "Giới hạn của TPM(Token per minute) là từ 0 đến 250000")]
    [DefaultValue(250000)]
    public int TpmLimit { get; set; }

    /// <summary>
    /// Giới hạn số request mỗi ngày (Requests Per Day).
    /// </summary>
    /// <example>20</example>
    [Required]
    [Range(0, 20, ErrorMessage = "Giới hạn của RPD(Requests per day) là từ 0 đến 20")]
    [DefaultValue(20)]
    public int RpdLimit { get; set; }

    /// <summary>
    /// Số request đã sử dụng trong ngày hôm nay.
    /// </summary>
    /// <remarks>
    /// Thường đặt là 0 khi tạo mới. Hệ thống sẽ tự động reset sau 24h.
    /// </remarks>
    /// <example>0</example>
    [Required]
    [Range(0, int.MaxValue)]
    [DefaultValue(0)]
    public int RequestsUsedToday { get; set; }

    /// <summary>
    /// Số token đã sử dụng trong ngày hôm nay.
    /// </summary>
    /// <remarks>
    /// Thường đặt là 0 khi tạo mới.
    /// </remarks>
    /// <example>0</example>
    [Required]
    [Range(0, long.MaxValue)]
    [DefaultValue(0)]
    public long TokensUsedToday { get; set; }

    public DateTime LastResetDate { get; set; }

    public DateTime? RateLimitedUntil { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}