// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class InterestByRegion
{
    public int Id { get; set; }

    public int TrendSearchId { get; set; }

    public string LocationName { get; set; }

    public int InterestValue { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual TrendSearch TrendSearch { get; set; }
}