// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

[Table("InterestOverTime")]
[Index("TrendSearchId", Name = "IX_InterestOverTime_TrendSearchId")]
public partial class InterestOverTime
{
    [Key]
    public int Id { get; set; }

    public int TrendSearchId { get; set; }

    [Required]
    [StringLength(255)]
    public string Query { get; set; }

    [StringLength(100)]
    public string DateRange { get; set; }

    public long? TimestampVal { get; set; }

    public int InterestValue { get; set; }

    [ForeignKey("TrendSearchId")]
    [InverseProperty("InterestOverTimes")]
    public virtual TrendSearch TrendSearch { get; set; }
}