// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class MetaDataSuggestion
{
    public int Id { get; set; }

    public int MetaDataAnalysisId { get; set; }

    public string GeneralAssessment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual MetaDataAnalysis MetaDataAnalysis { get; set; }

    public virtual ICollection<MetaTagSuggestionDetail> MetaTagSuggestionDetails { get; set; } = new List<MetaTagSuggestionDetail>();
}