// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class MetaTagSuggestionDetail
{
    [Key]
    public int Id { get; set; }

    public int MetaDataSuggestionId { get; set; }

    [Required]
    [StringLength(100)]
    public string TagName { get; set; }

    public string CurrentValue { get; set; }

    public string Issue { get; set; }

    public string Recommendation { get; set; }

    public bool? IsImportant { get; set; }

    public DateTime? CreatedAt { get; set; }

    [ForeignKey("MetaDataSuggestionId")]
    [InverseProperty("MetaTagSuggestionDetails")]
    public virtual MetaDataSuggestion MetaDataSuggestion { get; set; }
}