// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class MetaDataSuggestion
{
    [Key]
    public int Id { get; set; }

    public int MetaDataAnalysisId { get; set; }

    public string GeneralAssessment { get; set; }

    public DateTime? CreatedAt { get; set; }

    [ForeignKey("MetaDataAnalysisId")]
    [InverseProperty("MetaDataSuggestions")]
    public virtual MetaDataAnalysis MetaDataAnalysis { get; set; }

    [InverseProperty("MetaDataSuggestion")]
    public virtual ICollection<MetaTagSuggestionDetail> MetaTagSuggestionDetails { get; set; } = new List<MetaTagSuggestionDetail>();
}