// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class MetaDataAnalysis
{
    public int Id { get; set; }

    public string Url { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Keywords { get; set; }

    public string Charset { get; set; }

    public string Viewport { get; set; }

    public string Canonical { get; set; }

    public string Robots { get; set; }

    public string OpenGraphData { get; set; }

    public string TwitterCardData { get; set; }

    public string OtherMetaData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public byte[] UrlHash { get; set; }

    public int? AnalysisCacheID { get; set; }

    public virtual AnalysisCache AnalysisCache { get; set; }

    public virtual ICollection<MetaDataSuggestion> MetaDataSuggestions { get; set; } = new List<MetaDataSuggestion>();
}