// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class PerformanceHistory
{
    [Key]
    public int ScanHistoryID { get; set; }

    public int UserID { get; set; }

    public int AnalysisCacheID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScanTime { get; set; }

    [ForeignKey("AnalysisCacheID")]
    [InverseProperty("PerformanceHistories")]
    public virtual AnalysisCache AnalysisCache { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("PerformanceHistories")]
    public virtual User User { get; set; }
}