// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class PerformanceHistory
{
    public int ScanHistoryID { get; set; }

    public int UserID { get; set; }

    public int AnalysisCacheID { get; set; }

    public DateTime ScanTime { get; set; }

    public virtual AnalysisCache AnalysisCache { get; set; }

    public virtual User User { get; set; }
}