// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class Performance
{
    [Key]
    public int PerformanceID { get; set; }

    public int UserID { get; set; }

    [Required]
    [StringLength(255)]
    public string Url { get; set; }

    [Required]
    public string PageSpeedResponse { get; set; }

    public string GeneralAssessment { get; set; }

    public string Suggestion { get; set; }

    [StringLength(50)]
    public string Strategy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FetchTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CompletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Performance")]
    public virtual ICollection<Element> Elements { get; set; } = new List<Element>();

    [ForeignKey("UserID")]
    [InverseProperty("Performances")]
    public virtual User User { get; set; }
}