// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class PurchasedFeature
{
    [Key]
    public int ID { get; set; }

    public int UserID { get; set; }

    public int FeatureID { get; set; }

    public int? TransactionID { get; set; }

    public int TotalQuantity { get; set; }

    public int RemainingQuantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PurchaseDate { get; set; }

    [ForeignKey("FeatureID")]
    [InverseProperty("PurchasedFeatures")]
    public virtual Feature Feature { get; set; }

    [ForeignKey("TransactionID")]
    [InverseProperty("PurchasedFeatures")]
    public virtual Transaction Transaction { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("PurchasedFeatures")]
    public virtual User User { get; set; }
}