// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class PurchasedFeature
{
    public int PurchasedFeatureID { get; set; }

    public int FeatureID { get; set; }

    public int TransactionID { get; set; }

    public int TotalQuantity { get; set; }

    public int RemainingQuantity { get; set; }

    public DateTime PurchaseDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Feature Feature { get; set; }

    public virtual Transaction Transaction { get; set; }
}