// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class QueryHistory
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string OriginalQuestion { get; set; }

    public string FinalAiResponse { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? AdsSearchRequestId { get; set; }

    public virtual AdsSearchRequest AdsSearchRequest { get; set; }

    public virtual User Member { get; set; }
}