// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

public partial class QuestionData
{
    [Key]
    public int ID { get; set; }

    public int UserID { get; set; }

    [Required]
    [StringLength(255)]
    public string Question { get; set; }

    public string DataResponse { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("QuestionData")]
    public virtual User User { get; set; }
}