// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class RegionComparison
{
    public int Id { get; set; }

    public int TrendSearchId { get; set; }

    public string LocationName { get; set; }

    public string Query { get; set; }

    public int InterestPercentage { get; set; }

    public virtual TrendSearch TrendSearch { get; set; }
}