// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class RelatedTopic
{
    public int Id { get; set; }

    public int TrendSearchId { get; set; }

    public string Category { get; set; }

    public string TopicTitle { get; set; }

    public string TopicType { get; set; }

    public string ValueString { get; set; }

    public int ExtractedValue { get; set; }

    public string GoogleTrendsLink { get; set; }

    public virtual TrendSearch TrendSearch { get; set; }
}