// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class SEP_SEOBoostAIContext : DbContext
{
    public SEP_SEOBoostAIContext()
    {
    }

    public SEP_SEOBoostAIContext(DbContextOptions<SEP_SEOBoostAIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdsKeywordDatum> AdsKeywordData { get; set; }

    public virtual DbSet<AdsSearchRequest> AdsSearchRequests { get; set; }

    public virtual DbSet<AnalysisCache> AnalysisCaches { get; set; }

    public virtual DbSet<AnalysisSnapshot> AnalysisSnapshots { get; set; }

    public virtual DbSet<ContentOptimization> ContentOptimizations { get; set; }

    public virtual DbSet<Element> Elements { get; set; }

    public virtual DbSet<Feature> Features { get; set; }

    public virtual DbSet<FeatureInformation> FeatureInformations { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<FeedbackMessage> FeedbackMessages { get; set; }

    public virtual DbSet<GeminiKey> GeminiKeys { get; set; }

    public virtual DbSet<InterestByRegion> InterestByRegions { get; set; }

    public virtual DbSet<InterestOverTime> InterestOverTimes { get; set; }

    public virtual DbSet<MetaDataAnalysis> MetaDataAnalyses { get; set; }

    public virtual DbSet<MetaDataSuggestion> MetaDataSuggestions { get; set; }

    public virtual DbSet<MetaTagSuggestionDetail> MetaTagSuggestionDetails { get; set; }

    public virtual DbSet<PerformanceHistory> PerformanceHistorys { get; set; }

    public virtual DbSet<PurchasedFeature> PurchasedFeatures { get; set; }

    public virtual DbSet<QueryHistory> QueryHistories { get; set; }

    public virtual DbSet<RegionComparison> RegionComparisons { get; set; }

    public virtual DbSet<RelatedQuery> RelatedQueries { get; set; }

    public virtual DbSet<RelatedTopic> RelatedTopics { get; set; }

    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<TrendSearch> TrendSearches { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserMonthlyFreeQuota> UserMonthlyFreeQuotas { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=HANAYUKI;Initial Catalog=SEP_SEOBoostAI;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdsKeywordDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdsKeywo__3214EC0745668EE9");

            entity.HasOne(d => d.AdsSearchRequest).WithMany(p => p.AdsKeywordData).HasConstraintName("FK__AdsKeywor__AdsSe__2739D489");
        });

        modelBuilder.Entity<AdsSearchRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdsSearc__3214EC071E236965");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.QueryHash)
                .HasComputedColumnSql("(CONVERT([binary](32),hashbytes('SHA2_256',CONVERT([varbinary](max),[QueryList]))))", true)
                .IsFixedLength();
        });

        modelBuilder.Entity<AnalysisCache>(entity =>
        {
            entity.HasKey(e => e.AnalysisCacheID).HasName("PK__Analysis__64960DCD15D9ED48");

            entity.Property(e => e.LastAnalyzedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AnalysisSnapshot>(entity =>
        {
            entity.HasKey(e => e.SnapshotID).HasName("PK__Analysis__664F570B525CA303");

            entity.Property(e => e.ArchivedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.AnalysisSnapshots).HasConstraintName("FK_AnalysisSnapshot_AnalysisCache");
        });

        modelBuilder.Entity<ContentOptimization>(entity =>
        {
            entity.HasKey(e => e.ContentOptimizationID).HasName("PK__ContentO__27E3172DAC4FFF96");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.ContentOptimizations).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Element>(entity =>
        {
            entity.HasKey(e => e.ElementID).HasName("PK__Elements__A429723A72479341");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.Elements).HasConstraintName("FK_Elements_AnalysisCache");
        });

        modelBuilder.Entity<Feature>(entity =>
        {
            entity.HasKey(e => e.FeatureID).HasName("PK__Features__82230A29205A444C");
        });

        modelBuilder.Entity<FeatureInformation>(entity =>
        {
            entity.HasKey(e => e.InformationID).HasName("PK__FeatureI__C93C35D0D8F38EE6");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Feature).WithMany(p => p.FeatureInformations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Information_Feature");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackID).HasName("PK__Feedback__6A4BEDF628D67B9C");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Feedbacks_CreatedAt");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Feedbacks_UpdatedAt");
        });

        modelBuilder.Entity<FeedbackMessage>(entity =>
        {
            entity.HasKey(e => e.MessageID).HasName("PK__Feedback__C87C037C8B3C78B3");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Sender).WithMany(p => p.FeedbackMessages).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<GeminiKey>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GeminiKe__3214EC0720171F8C");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastResetDate).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.RpdLimit).HasDefaultValue(250);
            entity.Property(e => e.RpmLimit).HasDefaultValue(10);
            entity.Property(e => e.TpmLimit).HasDefaultValue(250000);
        });

        modelBuilder.Entity<InterestByRegion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Interest__3214EC07887292DF");

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.InterestByRegions).HasConstraintName("FK__InterestB__Trend__160F4887");
        });

        modelBuilder.Entity<InterestOverTime>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Interest__3214EC0705FA47E4");

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.InterestOverTimes).HasConstraintName("FK__InterestO__Trend__0F624AF8");
        });

        modelBuilder.Entity<MetaDataAnalysis>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MetaData__3214EC07A1EF1E13");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UrlHash).HasComputedColumnSql("(CONVERT([varbinary](32),hashbytes('SHA2_256',[Url])))", false);

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.MetaDataAnalyses).HasConstraintName("FK_MetaDataAnalysis_AnalysisCache");
        });

        modelBuilder.Entity<MetaDataSuggestion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MetaData__3214EC07247ED252");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.MetaDataAnalysis).WithMany(p => p.MetaDataSuggestions).HasConstraintName("FK__MetaDataS__MetaD__40F9A68C");
        });

        modelBuilder.Entity<MetaTagSuggestionDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MetaTagS__3214EC07E5ED0CCA");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsImportant).HasDefaultValue(false);

            entity.HasOne(d => d.MetaDataSuggestion).WithMany(p => p.MetaTagSuggestionDetails).HasConstraintName("FK__MetaTagSu__MetaD__45BE5BA9");
        });

        modelBuilder.Entity<PerformanceHistory>(entity =>
        {
            entity.HasKey(e => e.ScanHistoryID).HasName("PK__Performa__3AC3D457691F772A");

            entity.Property(e => e.ScanTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.PerformanceHistories).HasConstraintName("FK_History_AnalysisCache");

            entity.HasOne(d => d.User).WithMany(p => p.PerformanceHistories).HasConstraintName("FK_History_Users");
        });

        modelBuilder.Entity<PurchasedFeature>(entity =>
        {
            entity.HasKey(e => e.PurchasedFeatureID).HasName("PK__Purchase__2DD96E5316949213");

            entity.Property(e => e.PurchaseDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<QueryHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__QueryHis__3214EC079826C96A");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.AdsSearchRequest).WithMany(p => p.QueryHistories).HasConstraintName("FK_QueryHistory_AdsSearchRequests");

            entity.HasOne(d => d.Member).WithMany(p => p.QueryHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__QueryHist__Membe__208CD6FA");
        });

        modelBuilder.Entity<RegionComparison>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RegionCo__3214EC07C373517D");

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.RegionComparisons).HasConstraintName("FK__RegionCom__Trend__1CBC4616");
        });

        modelBuilder.Entity<RelatedQuery>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RelatedQ__3214EC07E657F408");

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.RelatedQueries).HasConstraintName("FK__RelatedQu__Trend__18EBB532");
        });

        modelBuilder.Entity<RelatedTopic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RelatedT__3214EC077742A1AA");

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.RelatedTopics).HasConstraintName("FK__RelatedTo__Trend__123EB7A3");
        });

        modelBuilder.Entity<SystemSetting>(entity =>
        {
            entity.HasKey(e => e.SettingID).HasName("PK_SystemSettings_New");

            entity.Property(e => e.LastUpdatedDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionID).HasName("PK__Transact__55433A4B17E6CEDD");

            entity.Property(e => e.RequestTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("PENDING");

            entity.HasOne(d => d.User).WithMany(p => p.Transactions).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TrendSearch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TrendSea__3214EC07BEAA6EF6");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__Users__1788CCAC9D5C8781");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserMonthlyFreeQuota>(entity =>
        {
            entity.HasKey(e => e.UserMonthlyFreeQuotaID).HasName("PK__UserMont__3A7DB1E096195171");

            entity.Property(e => e.MonthYear).IsFixedLength();
            entity.Property(e => e.MonthlyLimit).HasDefaultValue(3);

            entity.HasOne(d => d.Feature).WithMany(p => p.UserMonthlyFreeQuota).HasConstraintName("FK_UserMonthlyFreeQuota_Features_FeatureID");

            entity.HasOne(d => d.User).WithMany(p => p.UserMonthlyFreeQuota).HasConstraintName("FK_UserMonthlyFreeQuota_Users_UserID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}