// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class SEP_SEOBoostAIContext : DbContext
{
    public SEP_SEOBoostAIContext()
    {
    }

    public SEP_SEOBoostAIContext(DbContextOptions<SEP_SEOBoostAIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdsKeywordDatum> AdsKeywordData { get; set; }

    public virtual DbSet<AdsSearchRequest> AdsSearchRequests { get; set; }

    public virtual DbSet<AnalysisCache> AnalysisCaches { get; set; }

    public virtual DbSet<AnalysisSnapshot> AnalysisSnapshots { get; set; }

    public virtual DbSet<ContentOptimization> ContentOptimizations { get; set; }

    public virtual DbSet<Element> Elements { get; set; }

    public virtual DbSet<Feature> Features { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<FeedbackMessage> FeedbackMessages { get; set; }

    public virtual DbSet<InterestByRegion> InterestByRegions { get; set; }

    public virtual DbSet<InterestOverTime> InterestOverTimes { get; set; }

    public virtual DbSet<PerformanceHistory> PerformanceHistorys { get; set; }

    public virtual DbSet<PurchasedFeature> PurchasedFeatures { get; set; }

    public virtual DbSet<QueryHistory> QueryHistories { get; set; }

    public virtual DbSet<RegionComparison> RegionComparisons { get; set; }

    public virtual DbSet<RelatedQuery> RelatedQueries { get; set; }

    public virtual DbSet<RelatedTopic> RelatedTopics { get; set; }

    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<TrendSearch> TrendSearches { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserMonthlyFreeQuota> UserMonthlyFreeQuotas { get; set; }

    public virtual DbSet<Wallet> Wallets { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-M0B2NAEA\\SQLEXPRESS;Initial Catalog=SEP_SEOBoostAI;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdsKeywordDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdsKeywo__3214EC07D1E4D307");

            entity.Property(e => e.AvgSearchVolume).HasMaxLength(50);
            entity.Property(e => e.Competition).HasMaxLength(50);
            entity.Property(e => e.HighBid).HasMaxLength(50);
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.LowBid).HasMaxLength(50);

            entity.HasOne(d => d.AdsSearchRequest).WithMany(p => p.AdsKeywordData)
                .HasForeignKey(d => d.AdsSearchRequestId)
                .HasConstraintName("FK__AdsKeywor__AdsSe__45BE5BA9");
        });

        modelBuilder.Entity<AdsSearchRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdsSearc__3214EC073A9ED2A0");

            entity.HasIndex(e => e.QueryHash, "IX_AdsSearchRequests_QueryHash");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.QueryHash)
                .HasMaxLength(8000)
                .HasComputedColumnSql("(hashbytes('SHA2_256',CONVERT([varbinary](max),[QueryList])))", true);
            entity.Property(e => e.QueryList).IsRequired();
        });

        modelBuilder.Entity<AnalysisCache>(entity =>
        {
            entity.HasKey(e => e.AnalysisCacheID).HasName("PK__Analysis__64960DCD7E3255CF");

            entity.ToTable("AnalysisCache");

            entity.HasIndex(e => e.NormalizedUrl, "IX_AnalysisCache_NormalizedUrl");

            entity.HasIndex(e => new { e.NormalizedUrl, e.Strategy }, "UQ_AnalysisCache_NormalizedUrl_Strategy").IsUnique();

            entity.Property(e => e.LastAnalyzedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NormalizedUrl)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PageSpeedResponse).IsRequired();
            entity.Property(e => e.Strategy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<AnalysisSnapshot>(entity =>
        {
            entity.HasKey(e => e.SnapshotID).HasName("PK__Analysis__664F570B606BCB0C");

            entity.ToTable("AnalysisSnapshot");

            entity.Property(e => e.AnalyzedAt).HasColumnType("datetime");
            entity.Property(e => e.ArchivedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.AnalysisSnapshots)
                .HasForeignKey(d => d.AnalysisCacheID)
                .HasConstraintName("FK_AnalysisSnapshot_AnalysisCache");
        });

        modelBuilder.Entity<ContentOptimization>(entity =>
        {
            entity.HasKey(e => e.ContentOptimizationID).HasName("PK__ContentO__27E3172DA7D43B50");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Model).HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.ContentOptimizations)
                .HasForeignKey(d => d.UserID)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Element>(entity =>
        {
            entity.HasKey(e => e.ElementID).HasName("PK__Elements__A429723A64EEFDAE");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.TagName).HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.Elements)
                .HasForeignKey(d => d.AnalysisCacheID)
                .HasConstraintName("FK_Elements_AnalysisCache");
        });

        modelBuilder.Entity<Feature>(entity =>
        {
            entity.HasKey(e => e.FeatureID).HasName("PK__Features__82230A290686B646");

            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackID).HasName("PK__Feedback__6A4BEDF6BB88E786");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Feedbacks_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.Topic).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Feedbacks_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.Feedbacks).HasForeignKey(d => d.UserID);
        });

        modelBuilder.Entity<FeedbackMessage>(entity =>
        {
            entity.HasKey(e => e.MessageID).HasName("PK__Feedback__C87C037CE059E400");

            entity.HasIndex(e => e.FeedbackID, "IX_FeedbackMessages_FeedbackID");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Feedback).WithMany(p => p.FeedbackMessages).HasForeignKey(d => d.FeedbackID);

            entity.HasOne(d => d.Sender).WithMany(p => p.FeedbackMessages)
                .HasForeignKey(d => d.SenderID)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<InterestByRegion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Interest__3214EC07B3F8A78D");

            entity.ToTable("InterestByRegion");

            entity.HasIndex(e => e.TrendSearchId, "IX_InterestByRegion_TrendSearchId");

            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Longitude).HasColumnType("decimal(11, 8)");

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.InterestByRegions)
                .HasForeignKey(d => d.TrendSearchId)
                .HasConstraintName("FK__InterestB__Trend__0C85DE4D");
        });

        modelBuilder.Entity<InterestOverTime>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Interest__3214EC07A96A35F8");

            entity.ToTable("InterestOverTime");

            entity.HasIndex(e => e.TrendSearchId, "IX_InterestOverTime_TrendSearchId");

            entity.Property(e => e.DateRange).HasMaxLength(100);
            entity.Property(e => e.Query)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.InterestOverTimes)
                .HasForeignKey(d => d.TrendSearchId)
                .HasConstraintName("FK__InterestO__Trend__05D8E0BE");
        });

        modelBuilder.Entity<PerformanceHistory>(entity =>
        {
            entity.HasKey(e => e.ScanHistoryID).HasName("PK__Performa__3AC3D45749E74ADC");

            entity.Property(e => e.ScanTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.AnalysisCache).WithMany(p => p.PerformanceHistories)
                .HasForeignKey(d => d.AnalysisCacheID)
                .HasConstraintName("FK_History_AnalysisCache");

            entity.HasOne(d => d.User).WithMany(p => p.PerformanceHistories)
                .HasForeignKey(d => d.UserID)
                .HasConstraintName("FK_History_Users");
        });

        modelBuilder.Entity<PurchasedFeature>(entity =>
        {
            entity.HasKey(e => e.PurchasedFeatureID).HasName("PK__Purchase__2DD96E538B377EB3");

            entity.Property(e => e.PurchaseDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Feature).WithMany(p => p.PurchasedFeatures).HasForeignKey(d => d.FeatureID);

            entity.HasOne(d => d.Transaction).WithMany(p => p.PurchasedFeatures).HasForeignKey(d => d.TransactionID);
        });

        modelBuilder.Entity<QueryHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__QueryHis__3214EC07D4E3FDDE");

            entity.ToTable("QueryHistory");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FinalAiResponse).IsRequired();
            entity.Property(e => e.OriginalQuestion)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.AdsSearchRequest).WithMany(p => p.QueryHistories)
                .HasForeignKey(d => d.AdsSearchRequestId)
                .HasConstraintName("FK_QueryHistory_AdsSearchRequests");

            entity.HasOne(d => d.Member).WithMany(p => p.QueryHistories)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__QueryHist__Membe__17036CC0");
        });

        modelBuilder.Entity<RegionComparison>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RegionCo__3214EC07D3A87487");

            entity.ToTable("RegionComparison");

            entity.HasIndex(e => e.TrendSearchId, "IX_RegionComparison_TrendSearchId");

            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Query)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.RegionComparisons)
                .HasForeignKey(d => d.TrendSearchId)
                .HasConstraintName("FK__RegionCom__Trend__1332DBDC");
        });

        modelBuilder.Entity<RelatedQuery>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RelatedQ__3214EC0706937F3D");

            entity.HasIndex(e => e.TrendSearchId, "IX_RelatedQueries_TrendSearchId");

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Query)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.RelatedQueries)
                .HasForeignKey(d => d.TrendSearchId)
                .HasConstraintName("FK__RelatedQu__Trend__0F624AF8");
        });

        modelBuilder.Entity<RelatedTopic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RelatedT__3214EC071CBBB13F");

            entity.HasIndex(e => e.TrendSearchId, "IX_RelatedTopics_TrendSearchId");

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.GoogleTrendsLink).HasColumnType("text");
            entity.Property(e => e.TopicTitle)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TopicType).HasMaxLength(255);
            entity.Property(e => e.ValueString)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.TrendSearch).WithMany(p => p.RelatedTopics)
                .HasForeignKey(d => d.TrendSearchId)
                .HasConstraintName("FK__RelatedTo__Trend__08B54D69");
        });

        modelBuilder.Entity<SystemSetting>(entity =>
        {
            entity.HasKey(e => e.SettingKey).HasName("PK__SystemSe__01E719AC9DC724D5");

            entity.Property(e => e.SettingKey).HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.LastUpdatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SettingValue)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionID).HasName("PK__Transact__55433A4B6DCF097F");

            entity.HasIndex(e => e.GatewayTransactionId, "UQ__Transact__CAD5B8E65B3D00EC").IsUnique();

            entity.Property(e => e.BankTransId).HasMaxLength(100);
            entity.Property(e => e.CompletedTime).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.GatewayTransactionId).HasMaxLength(100);
            entity.Property(e => e.Money).HasColumnType("money");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.RequestTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("PENDING");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Wallet).WithMany(p => p.Transactions).HasForeignKey(d => d.WalletID);
        });

        modelBuilder.Entity<TrendSearch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TrendSea__3214EC0738F5A420");

            entity.HasIndex(e => new { e.Query, e.Geolocation, e.Timeframe, e.Language, e.CreatedAt }, "IX_TrendSearches_CacheCheck");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Geolocation)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Language)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Query)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Timeframe)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__Users__1788CCAC37ECD5F1");

            entity.HasIndex(e => e.UserName, "UQ__Users__C9F28456695A751E").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.Role).HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<UserMonthlyFreeQuota>(entity =>
        {
            entity.HasKey(e => e.UserMonthlyFreeQuotaID).HasName("PK__UserMont__3A7DB1E024543B76");

            entity.HasIndex(e => new { e.UserID, e.FeatureID, e.MonthYear }, "UQ_UserMonthlyQuota").IsUnique();

            entity.Property(e => e.LastUsedAt).HasColumnType("datetime");
            entity.Property(e => e.MonthYear)
                .IsRequired()
                .HasMaxLength(7)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MonthlyLimit).HasDefaultValue(3);

            entity.HasOne(d => d.Feature).WithMany(p => p.UserMonthlyFreeQuota)
                .HasForeignKey(d => d.FeatureID)
                .HasConstraintName("FK_UserMonthlyFreeQuota_Features_FeatureID");

            entity.HasOne(d => d.User).WithMany(p => p.UserMonthlyFreeQuota)
                .HasForeignKey(d => d.UserID)
                .HasConstraintName("FK_UserMonthlyFreeQuota_Users_UserID");
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.HasKey(e => e.WalletID).HasName("PK__Wallets__84D4F92E8A5A665E");

            entity.HasIndex(e => e.UserID, "UQ__Wallets__1788CCAD4A18C0AB").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Currency).HasColumnType("money");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithOne(p => p.Wallet).HasForeignKey<Wallet>(d => d.UserID);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}