// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class Transaction
{
    public int TransactionID { get; set; }

    public int WalletID { get; set; }

    public decimal Money { get; set; }

    public string GatewayTransactionId { get; set; }

    public string BankTransId { get; set; }

    public string PaymentMethod { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime RequestTime { get; set; }

    public DateTime? CompletedTime { get; set; }

    public bool IsDeleted { get; set; }

    public decimal? BalanceAfter { get; set; }

    public virtual ICollection<PurchasedFeature> PurchasedFeatures { get; set; } = new List<PurchasedFeature>();

    public virtual Wallet Wallet { get; set; }
}