// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

[Index("GatewayTransactionId", Name = "UQ_Transactions_GatewayTransactionId", IsUnique = true)]
public partial class Transaction
{
    [Key]
    public int TransactionID { get; set; }

    public int UserID { get; set; }

    [Column(TypeName = "money")]
    public decimal Money { get; set; }

    [StringLength(100)]
    public string GatewayTransactionId { get; set; }

    [StringLength(100)]
    public string BankTransId { get; set; }

    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RequestTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CompletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BalanceAfter { get; set; }

    [InverseProperty("Transaction")]
    public virtual ICollection<PurchasedFeature> PurchasedFeatures { get; set; } = new List<PurchasedFeature>();

    [ForeignKey("UserID")]
    [InverseProperty("Transactions")]
    public virtual User User { get; set; }
}