// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class TrendSearch
{
    public int Id { get; set; }

    public string Query { get; set; }

    public string Geolocation { get; set; }

    public string Language { get; set; }

    public string Timeframe { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<InterestByRegion> InterestByRegions { get; set; } = new List<InterestByRegion>();

    public virtual ICollection<InterestOverTime> InterestOverTimes { get; set; } = new List<InterestOverTime>();

    public virtual ICollection<RegionComparison> RegionComparisons { get; set; } = new List<RegionComparison>();

    public virtual ICollection<RelatedQuery> RelatedQueries { get; set; } = new List<RelatedQuery>();

    public virtual ICollection<RelatedTopic> RelatedTopics { get; set; } = new List<RelatedTopic>();
}