// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class UserMonthlyFreeQuota
{
    public int UserMonthlyFreeQuotaID { get; set; }

    public int UserID { get; set; }

    public int FeatureID { get; set; }

    public string MonthYear { get; set; }

    public int MonthlyLimit { get; set; }

    public int UsageCount { get; set; }

    public DateTime? LastUsedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Feature Feature { get; set; }

    public virtual User User { get; set; }
}