// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SEOBoostAI.Repository.Models;

[Index("Username", Name = "UQ__Users__536C85E4AF96C7CF", IsUnique = true)]
public partial class User
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(255)]
    public string Username { get; set; }

    [StringLength(255)]
    public string Password { get; set; }

    [Required]
    [StringLength(255)]
    public string FullName { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    public string Avatar { get; set; }

    public string GoogleID { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<ContentOptimization> ContentOptimizations { get; set; } = new List<ContentOptimization>();

    [InverseProperty("User")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("User")]
    public virtual ICollection<Performance> Performances { get; set; } = new List<Performance>();

    [InverseProperty("User")]
    public virtual ICollection<UserMonthlyFreeQuotum> UserMonthlyFreeQuota { get; set; } = new List<UserMonthlyFreeQuotum>();

    [InverseProperty("User")]
    public virtual Wallet Wallet { get; set; }
}