// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class User
{
    public int UserID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Role { get; set; }

    public string Avatar { get; set; }

    public string GoogleID { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsBanned { get; set; }

    public bool IsDeleted { get; set; }

    public decimal Currency { get; set; }

    public virtual ICollection<ContentOptimization> ContentOptimizations { get; set; } = new List<ContentOptimization>();

    public virtual ICollection<FeedbackMessage> FeedbackMessages { get; set; } = new List<FeedbackMessage>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<PerformanceHistory> PerformanceHistories { get; set; } = new List<PerformanceHistory>();

    public virtual ICollection<QueryHistory> QueryHistories { get; set; } = new List<QueryHistory>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<UserMonthlyFreeQuota> UserMonthlyFreeQuota { get; set; } = new List<UserMonthlyFreeQuota>();
}